In [1]:
#IMPORTING LIBRARIES:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('labeled_data.csv')
df

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [3]:
#any null values:
df.isnull().sum()

Unnamed: 0            0
count                 0
hate_speech           0
offensive_language    0
neither               0
class                 0
tweet                 0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          24783 non-null  int64 
 1   count               24783 non-null  int64 
 2   hate_speech         24783 non-null  int64 
 3   offensive_language  24783 non-null  int64 
 4   neither             24783 non-null  int64 
 5   class               24783 non-null  int64 
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB


In [5]:
#lets see number of unique classes present in the dataset:
df['class'].nunique()

3

In [6]:
def make_label(x):
    if x == 0:
        return 'Hate Speech'
    if x == 1:
        return 'Offensive Language'
    else:
        return 'No Hate Nor Offensive'
df['label'] = df['class'].apply(make_label)
df

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  \
0      !!! RT @mayasolovely: As a woman you shouldn't...   
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   
...                                                  ...   
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...   
24779  you've gone and broke the wrong heart baby, an...   
24780  young buck wanna eat!!.. dat nigguh like I ain...   
24781              youu got wild bitches tellin you lies   
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...   

                       label  
0      No Hate Nor Offensive  
1         Offensive Language  
2         Offensive Language  
3         Offensive Language  
4         Offensive Language  
...                      ...  
24778     Offensive Language  
24779  No Hate Nor Offensive  
24780     Offensive Language  
24781     Offensive Language  
24782  No Hate Nor Offensive  

[24783 rows x 8 columns]

In [7]:
#dropping down irrelevant columns:
data = df.drop(labels=['Unnamed: 0','count','hate_speech','offensive_language','neither','class'],axis = 1)
data

tweet  \
0      !!! RT @mayasolovely: As a woman you shouldn't...   
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   
...                                                  ...   
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...   
24779  you've gone and broke the wrong heart baby, an...   
24780  young buck wanna eat!!.. dat nigguh like I ain...   
24781              youu got wild bitches tellin you lies   
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...   

                       label  
0      No Hate Nor Offensive  
1         Offensive Language  
2         Offensive Language  
3         Offensive Language  
4         Offensive Language  
...                      ...  
24778     Offensive Language  
24779  No Hate Nor Offensive  
24780     Offensive Language  
24781     Offensive Language  
24782  No Hate Nor Offensive  

[24783 rows x 2 columns]

In [8]:
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')   # For tokenization
nltk.download('wordnet') # For WordNet Lemmatizer (a type of stemmer)
import string

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\swapn\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\swapn\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\swapn\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [9]:
from nltk.corpus import stopwords

In [10]:
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [11]:
stemmer = nltk.SnowballStemmer('english')

In [15]:
def pre_processing_data(text):
    text = str(text).lower() #you can see that datatype of text in df was object and hence we convrt it to string with lower keys
    text = re.sub(r'http?://\S+|www\.\S+', "", text) #getting rid of http and www. type of words
    text = re.sub("\[.*?\]","",text) #getting rid of question marks
    text = re.sub("<.*?>+","",text) #getting rid of HTML tags
    text = re.sub(r"[%s]" % re.escape(string.punctuation), "", text) #getting rid of punct.
    text = re.sub("\n","",text) #getting rid of next lines.
    text = re.sub("\w*\d\w*","",text) # remove words that contain digits from the 'text' variable. ex:ad23c
    
    #stop_word removal:
    text = [word for word in text.split(' ') if word not in stopwords]
    text = " ".join(text)
    
    #Stemming:
    text = [stemmer.stem(word) for word in text.split(' ')]
    text = " ".join(text)
    return text

In [16]:
data['tweet'] = data['tweet'].apply(pre_processing_data)
data

tweet  \
0       rt mayasolov woman complain clean hous amp ma...   
1       rt  boy dat coldtyga dwn bad cuffin dat hoe  ...   
2       rt urkindofbrand dawg rt  ever fuck bitch sta...   
3                  rt cganderson vivaba look like tranni   
4       rt shenikarobert shit hear might true might f...   
...                                                  ...   
24778  muthafin lie lifeask  coreyemanuel right tl tr...   
24779    gone broke wrong heart babi drove redneck crazi   
24780  young buck wanna eat dat nigguh like aint fuck...   
24781                     youu got wild bitch tellin lie   
24782  ruffl  ntac eileen dahlia  beauti color combin...   

                       label  
0      No Hate Nor Offensive  
1         Offensive Language  
2         Offensive Language  
3         Offensive Language  
4         Offensive Language  
...                      ...  
24778     Offensive Language  
24779  No Hate Nor Offensive  
24780     Offensive Language  
24781     Offensive Language  
24782  No Hate Nor Offensive  

[24783 rows x 2 columns]

In [17]:
x = np.array(data['tweet'])
y = np.array(data['label'])
x

array([' rt mayasolov woman complain clean hous amp man alway take trash',
       ' rt  boy dat coldtyga dwn bad cuffin dat hoe  place',
       ' rt urkindofbrand dawg rt  ever fuck bitch start cri confus shit',
       ..., 'young buck wanna eat dat nigguh like aint fuckin dis',
       'youu got wild bitch tellin lie',
       'ruffl  ntac eileen dahlia  beauti color combin pink orang yellow amp white coll '],
      dtype=object)

In [18]:
y

array(['No Hate Nor Offensive', 'Offensive Language',
       'Offensive Language', ..., 'Offensive Language',
       'Offensive Language', 'No Hate Nor Offensive'], dtype=object)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(x)

In [21]:
print(x.toarray().shape)
x.toarray()

(24783, 27041)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=23)

In [24]:
print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of x_train: (19826, 27041)
Shape of x_test: (4957, 27041)
Shape of y_train: (19826,)
Shape of y_test: (4957,)


In [25]:
#Using NAIVE_BAYES:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [26]:
y_pred = model.predict(x_test)

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                       precision    recall  f1-score   support

          Hate Speech       0.31      0.05      0.09       302
No Hate Nor Offensive       0.85      0.68      0.76       843
   Offensive Language       0.88      0.97      0.92      3812

             accuracy                           0.87      4957
            macro avg       0.68      0.57      0.59      4957
         weighted avg       0.84      0.87      0.84      4957



In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[  15,   27,  260],
       [   6,  577,  260],
       [  27,   77, 3708]], dtype=int64)

In [28]:
#Using Decision Tree:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
Y_pred = model.predict(x_test)

In [30]:
print(classification_report(y_test,Y_pred))

                       precision    recall  f1-score   support

          Hate Speech       0.38      0.35      0.36       302
No Hate Nor Offensive       0.79      0.84      0.81       843
   Offensive Language       0.93      0.92      0.92      3812

             accuracy                           0.87      4957
            macro avg       0.70      0.70      0.70      4957
         weighted avg       0.87      0.87      0.87      4957



In [32]:
cm = confusion_matrix(y_test,Y_pred)
cm

array([[ 105,   32,  165],
       [  23,  704,  116],
       [ 150,  150, 3512]], dtype=int64)